version: '3.8'

services:
  # Основное приложение ЛИП
  lip-app:
    build: .
    container_name: lip-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/lip-workshop
      - JWT_SECRET=your_secret_key_change_this_in_production
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - lip-network

  # База данных MongoDB
  mongo:
    image: mongo:latest
    container_name: lip-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - lip-network

networks:
  lip-network:
    driver: bridge

volumes:
  mongo-data: 